name: Build and Deploy Documentation to GitHub Pages

on:
  # Trigger on pushes to main branch
  push:
    branches: [ main, master ]
  
  # Trigger on pull requests to main branch (for testing)
  pull_request:
    branches: [ main, master ]
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js (for potential future frontend tools)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install DocFx
      run: dotnet tool install -g docfx
    
    - name: Restore .NET dependencies
      run: dotnet restore EC-Project.sln
    
    - name: Build .NET solution
      run: dotnet build EC-Project.sln --configuration Release --no-restore
    
    - name: Test .NET solution (optional - uncomment if you have tests)
      # run: dotnet test EC-Project.sln --configuration Release --no-build --verbosity normal
      run: echo "No tests configured yet"
    
    - name: Generate DocFx metadata
      run: |
        cd docfx_project
        docfx metadata docfx.json
    
    - name: Build DocFx documentation
      run: |
        cd docfx_project
        docfx build docfx.json
    
    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docfx_project/_site

  # Deployment job (only runs on main branch pushes)
  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
